In [1]:

import numpy as np
import pandas as pd

In [2]:
# df = pd.read_csv('train.csv')
X_train = pd.read_csv('X_train_mvh.csv')
X_test = pd.read_csv('X_test_mvh.csv')
y_train = pd.read_csv('y_train.csv')
y_test = pd.read_csv('y_test.csv')

In [3]:
X_train.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps
0,Male,43.0,Salesperson,6.5,6.0,45.0,7,Overweight,130/85,72.0,6000
1,Male,33.0,Doctor,6.0,6.0,30.0,8,Normal,125/80,72.0,5000
2,Male,35.0,Software Engineer,7.5,8.0,60.0,5,Normal Weight,120/80,70.0,8000
3,Female,59.0,Nurse,8.2,9.0,75.0,3,Overweight,140/95,68.0,7000
4,Female,29.0,Nurse,6.5,5.0,40.0,7,Normal Weight,132/87,78.0,4000

In [4]:
X_train['Gender'].value_counts()

Gender
Female    155
Male      144
Name: count, dtype: int64

In [5]:
X_train['Occupation'].value_counts()

Occupation
Nurse                   62
Engineer                53
Doctor                  53
Lawyer                  36
Teacher                 34
Accountant              32
Salesperson             22
Scientist                3
Software Engineer        2
Sales Representative     1
Manager                  1
Name: count, dtype: int64

In [6]:
X_train['BMI Category'].value_counts()

BMI Category
Normal           154
Overweight       120
Normal Weight     19
Obese              6
Name: count, dtype: int64

In [7]:
X_train.dtypes

Gender                      object
Age                        float64
Occupation                  object
Sleep Duration             float64
Quality of Sleep           float64
Physical Activity Level    float64
Stress Level                 int64
BMI Category                object
Blood Pressure              object
Heart Rate                 float64
Daily Steps                  int64
dtype: object

In [8]:
X_train.isnull().sum()

Gender                     0
Age                        0
Occupation                 0
Sleep Duration             0
Quality of Sleep           0
Physical Activity Level    0
Stress Level               0
BMI Category               0
Blood Pressure             0
Heart Rate                 0
Daily Steps                0
dtype: int64

In [9]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')
X_train_ohe = ohe.fit_transform(X_train[['Gender','Occupation']]).astype('int64')
X_test_ohe = ohe.transform(X_test[['Gender','Occupation']]).astype('int64')

In [10]:
X_train_ohe

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [11]:
train_nominal_encoded_df = pd.DataFrame(X_train_ohe, 
                                        columns=ohe.get_feature_names_out(), 
                                        index=X_train.index)
test_nominal_encoded_df = pd.DataFrame(X_test_ohe, 
                                       columns=ohe.get_feature_names_out(), 
                                       index=X_test.index)
train_nominal_encoded_df

,Gender_Male,Occupation_Doctor,Occupation_Engineer,Occupation_Lawyer,Occupation_Manager,Occupation_Nurse,Occupation_Sales Representative,Occupation_Salesperson,Occupation_Scientist,Occupation_Software Engineer,Occupation_Teacher
0,1,0,0,0,0,0,0,1,0,0,0
1,1,1,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
294,1,1,0,0,0,0,0,0,0,0,0
295,0,0,0,0,0,1,0,0,0,0,0
296,0,0,0,0,0,1,0,0,0,0,0
297,0,0,0,0,0,1,0,0,0,0,0
298,0,0,0,0,0,0,0,0,0,0,1

In [12]:

X_train = X_train.drop(columns=['Gender','Occupation']).join(train_nominal_encoded_df)
X_test = X_test.drop(columns=['Gender','Occupation']).join(test_nominal_encoded_df)

X_train.shape

(299, 20)

In [13]:
#for multiple ordinal feature
from sklearn.preprocessing import OrdinalEncoder
ordinal_orders = [['Overweight','Normal','Normal Weight', 'Obese']]
oe = OrdinalEncoder(categories=ordinal_orders)
X_train[['BMI Category']] = oe.fit_transform(X_train[['BMI Category']])
X_test[['BMI Category']] = oe.transform(X_test[['BMI Category']])

In [14]:
train_ordinal_encoded_df = pd.DataFrame(X_train_ohe,
                                        columns=ohe.get_feature_names_out(),
                                        index=X_train.index)
test_ordinal_encoded_df = pd.DataFrame(X_test_ohe,
                                      columns=ohe.get_feature_names_out(),
                                        index=X_test.index) 
train_ordinal_encoded_df

,Gender_Male,Occupation_Doctor,Occupation_Engineer,Occupation_Lawyer,Occupation_Manager,Occupation_Nurse,Occupation_Sales Representative,Occupation_Salesperson,Occupation_Scientist,Occupation_Software Engineer,Occupation_Teacher
0,1,0,0,0,0,0,0,1,0,0,0
1,1,1,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
294,1,1,0,0,0,0,0,0,0,0,0
295,0,0,0,0,0,1,0,0,0,0,0
296,0,0,0,0,0,1,0,0,0,0,0
297,0,0,0,0,0,1,0,0,0,0,0
298,0,0,0,0,0,0,0,0,0,0,1

In [15]:
print(X_train[['BMI Category']].head())
print(X_test[['BMI Category']].head())

   BMI Category
0           0.0
1           1.0
2           2.0
3           0.0
4           2.0
   BMI Category
0           1.0
1           1.0
2           1.0
3           1.0
4           1.0

In [16]:
train_nominal_encoded_df = pd.DataFrame(X_train_ohe, 
                                        columns=ohe.get_feature_names_out(), 
                                        index=X_train.index)
test_nominal_encoded_df = pd.DataFrame(X_test_ohe, 
                                       columns=ohe.get_feature_names_out(), 
                                       index=X_test.index)
train_nominal_encoded_df

,Gender_Male,Occupation_Doctor,Occupation_Engineer,Occupation_Lawyer,Occupation_Manager,Occupation_Nurse,Occupation_Sales Representative,Occupation_Salesperson,Occupation_Scientist,Occupation_Software Engineer,Occupation_Teacher
0,1,0,0,0,0,0,0,1,0,0,0
1,1,1,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
294,1,1,0,0,0,0,0,0,0,0,0
295,0,0,0,0,0,1,0,0,0,0,0
296,0,0,0,0,0,1,0,0,0,0,0
297,0,0,0,0,0,1,0,0,0,0,0
298,0,0,0,0,0,0,0,0,0,0,1

In [17]:
train_ordinal_encoded_df = X_train[['BMI Category']]
test_ordinal_encoded_df = X_test[['BMI Category']]

In [18]:
# X_train = pd.concat((train_ordinal_encoded_df, train_nominal_encoded_df), axis=1)
# X_test = pd.concat((test_ordinal_encoded_df, test_nominal_encoded_df), axis=1)

In [19]:
X_train

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Gender_Male,Occupation_Doctor,Occupation_Engineer,Occupation_Lawyer,Occupation_Manager,Occupation_Nurse,Occupation_Sales Representative,Occupation_Salesperson,Occupation_Scientist,Occupation_Software Engineer,Occupation_Teacher
0,43.0,6.5,6.0,45.0,7,0.0,130/85,72.0,6000,1,0,0,0,0,0,0,1,0,0,0
1,33.0,6.0,6.0,30.0,8,1.0,125/80,72.0,5000,1,1,0,0,0,0,0,0,0,0,0
2,35.0,7.5,8.0,60.0,5,2.0,120/80,70.0,8000,1,0,0,0,0,0,0,0,0,1,0
3,59.0,8.2,9.0,75.0,3,0.0,140/95,68.0,7000,0,0,0,0,0,1,0,0,0,0,0
4,29.0,6.5,5.0,40.0,7,2.0,132/87,78.0,4000,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,33.0,6.1,6.0,30.0,8,1.0,125/80,72.0,5000,1,1,0,0,0,0,0,0,0,0,0
295,37.0,6.1,6.0,42.0,6,0.0,126/83,77.0,4200,0,0,0,0,0,1,0,0,0,0,0
296,49.0,6.1,6.0,90.0,8,0.0,140/95,75.0,10000,0,0,0,0,0,1,0,0,0,0,0
297,57.0,8.2,9.0,75.0,3,0.0,140/95,68.0,7000,0,0,0,0,0,1,0,0,0,0,0
298,36.0,7.2,8.0,60.0,4,1.0,115/75,68.0,7000,0,0,0,0,0,0,0,0,0,0,1

In [20]:
X_train.to_csv('X_train_enco.csv',index=False)
X_test.to_csv('X_test_encod.csv',index=False)
y_train.to_csv('y_train_tri.csv',index=False)
y_test.to_csv('y_test_traa.csv',index=False)